## Data Collection

Importing all the different packages

In [3]:
from espn_api.football import League
from espn_api.requests import EspnFantasyRequests
import os
from dotenv import load_dotenv
import json
import pandas as pd 
import time
import sys

project_root = os.path.abspath("..")  # Go up one level from notebooks/
scripts_path = os.path.join(project_root, "scripts")
if scripts_path not in sys.path:
    sys.path.append(scripts_path)

# Now import your functions
from utils import get_league_data, get_rostered_player_stats, save_to_data_raw

In [2]:
league = get_league_data(2024)

In [3]:
df_n = get_rostered_player_stats(league)

In [4]:
df_n

,,,,,points,avg_points,projected_points,projected_avg_points,actual_rushingAttempts,actual_rushingYards,actual_rushingTouchdowns,actual_rushing2PtConversions,actual_27,actual_28,...,actual_fumbleReturnTouchdowns,actual_228,actual_defensiveBlockedKickForTouchdowns,actual_defensive45PlusPointsAllowed,actual_196,actual_fumbleRecoveredForTD,actual_madeFieldGoalsFrom60Plus,actual_defensive2PtReturns,actual_puntFairCatches,actual_puntAverage38.0-39.9
player_name,player_id,team_name,team_id,acquisition_type,,,,,,,,,,,,,,,,,,,,,
Saquon Barkley,3929630,Stretchy Pups Elite,1,DRAFT,341.0,21.31,251.98,18.00,345.0,125.312500,13.0,3.0,395.0,191.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
De'Von Achane,4429160,Stretchy Pups Elite,1,DRAFT,286.0,16.82,210.02,15.00,203.0,53.352941,6.0,NaN,175.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Anthony Richardson,4429084,Stretchy Pups Elite,1,DRAFT,153.0,13.91,274.87,18.32,86.0,45.363636,6.0,1.0,96.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jaylen Waddle,4372016,Stretchy Pups Elite,1,DRAFT,142.0,9.47,217.93,14.53,4.0,0.800000,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Malik Nabers,4595348,Stretchy Pups Elite,1,DRAFT,266.0,17.73,221.80,14.79,5.0,0.133333,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Buccaneers D/ST,-16027,Joemomma,17,ADD,85.0,5.00,82.59,4.86,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Will Levis,4361418,Joemomma,17,ADD,111.0,9.25,228.76,15.25,45.0,15.250000,NaN,NaN,34.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Juwan Johnson,3929645,Joemomma,17,ADD,117.0,6.88,119.76,7.98,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ameer Abdullah,2576336,Joemomma,17,ADD,114.0,7.12,39.16,2.80,66.0,19.437500,2.0,NaN,57.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Marvin Mims Jr.,4686472,Joemomma,17,ADD,121.0,7.12,112.39,7.49,13.0,2.470588,NaN,NaN,6.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
save_to_data_raw(df_n, 'player_stats.csv')

File saved to: /Users/justinmckendry/ME204 Final Project/ME204 Final Project/data/raw/player_stats.csv

In [8]:
draft = league.espn_request.get_league_draft()
draft

{'draftDetail': {'completeDate': 1723771106392,
  'drafted': True,
  'inProgress': False,
  'picks': [{'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 1,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 1,
    'playerId': 3117251,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 1,
    'teamId': 3,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 2,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 2,
    'playerId': 4241389,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 2,
    'teamId': 14,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 3,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 3,
    'playerId': 3929630,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 3,
    'teamId': 1,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 4,
    'keeper': False,
    'lineupSlotId': 0,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 4,
    'playerId': 3918298,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 4,
    'teamId': 4,
    'tradeLocked': False},
   {'autoDraftTypeId': 3,
    'bidAmount': 0,
    'id': 5,
    'keeper': False,
    'lineupSlotId': 2,
    'nominatingTeamId': 0,
    'overallPickNumber': 5,
    'playerId': 4427366,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 5,
    'teamId': 8,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 6,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 6,
    'playerId': 3116406,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 6,
    'teamId': 10,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 7,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 7,
    'playerId': 4430807,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 7,
    'teamId': 6,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 8,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 8,
    'playerId': 4361529,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 8,
    'teamId': 16,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 9,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 9,
    'playerId': 4047646,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 9,
    'teamId': 11,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 10,
    'keeper': False,
    'lineupSlotId': 0,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 10,
    'playerId': 3916387,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 10,
    'teamId': 17,
    'tradeLocked': False},
   {'autoDraftTypeId': 1,
    'bidAmount': 0,
    'id': 11,
    'keeper': False,
    'lineupSlotId': 4,
    'nominatingTeamId': 0,
    'overallPickNumber': 11,
    'playerId': 4362628,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 11,
    'teamId': 12,
    'tradeLocked': False},
   {'autoDraftTypeId': 3,
    'bidAmount': 0,
    'id': 12,
    'keeper': False,
    'lineupSlotId': 4,
    'nominatingTeamId': 0,
    'overallPickNumber': 12,
    'playerId': 4374302,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 12,
    'teamId': 9,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 13,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 13,
    'playerId': 4262921,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 13,
    'teamId': 15,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 14,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 14,
    'playerId': 4426515,
    'reservedForKeeper': False,
    'roundId': 1,
    'roundPickNumber': 14,
    'teamId': 13,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 15,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 15,
    'playerId': 4429795,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 1,
    'teamId': 13,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 16,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 16,
    'playerId': 3043078,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 2,
    'teamId': 15,
    'tradeLocked': False},
   {'autoDraftTypeId': 3,
    'bidAmount': 0,
    'id': 17,
    'keeper': False,
    'lineupSlotId': 2,
    'nominatingTeamId': 0,
    'overallPickNumber': 17,
    'playerId': 4242335,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 3,
    'teamId': 9,
    'tradeLocked': False},
   {'autoDraftTypeId': 1,
    'bidAmount': 0,
    'id': 18,
    'keeper': False,
    'lineupSlotId': 4,
    'nominatingTeamId': 0,
    'overallPickNumber': 18,
    'playerId': 4569618,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 4,
    'teamId': 12,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 19,
    'keeper': False,
    'lineupSlotId': 6,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 19,
    'playerId': 15847,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 5,
    'teamId': 17,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 20,
    'keeper': False,
    'lineupSlotId': 0,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 20,
    'playerId': 4040715,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 6,
    'teamId': 11,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 21,
    'keeper': False,
    'lineupSlotId': 0,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 21,
    'playerId': 3139477,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 7,
    'teamId': 16,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 22,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 22,
    'playerId': 4430737,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 8,
    'teamId': 6,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 23,
    'keeper': False,
    'lineupSlotId': 0,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 23,
    'playerId': 3915511,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 9,
    'teamId': 10,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 24,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 24,
    'playerId': 4432708,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 10,
    'teamId': 8,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 25,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 25,
    'playerId': 2976212,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 11,
    'teamId': 4,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 26,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 26,
    'playerId': 4429160,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 12,
    'teamId': 1,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 27,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 27,
    'playerId': 4239996,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 13,
    'teamId': 14,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 28,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 28,
    'playerId': 4047365,
    'reservedForKeeper': False,
    'roundId': 2,
    'roundPickNumber': 14,
    'teamId': 3,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 29,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 29,
    'playerId': 3126486,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 1,
    'teamId': 3,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 30,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 30,
    'playerId': 16800,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 2,
    'teamId': 14,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 31,
    'keeper': False,
    'lineupSlotId': 0,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 31,
    'playerId': 4429084,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 3,
    'teamId': 1,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 32,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 32,
    'playerId': 4259545,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 4,
    'teamId': 4,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 33,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 33,
    'playerId': 4035687,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 5,
    'teamId': 8,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 34,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 34,
    'playerId': 4361370,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 6,
    'teamId': 10,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 35,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 35,
    'playerId': 4426502,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 7,
    'teamId': 6,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 36,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 36,
    'playerId': 3116385,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 8,
    'teamId': 16,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 37,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 37,
    'playerId': 3054850,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 9,
    'teamId': 11,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 38,
    'keeper': False,
    'lineupSlotId': 23,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 38,
    'playerId': 3121023,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 10,
    'teamId': 17,
    'tradeLocked': False},
   {'autoDraftTypeId': 1,
    'bidAmount': 0,
    'id': 39,
    'keeper': False,
    'lineupSlotId': 2,
    'nominatingTeamId': 0,
    'overallPickNumber': 39,
    'playerId': 4379399,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 11,
    'teamId': 12,
    'tradeLocked': False},
   {'autoDraftTypeId': 3,
    'bidAmount': 0,
    'id': 40,
    'keeper': False,
    'lineupSlotId': 4,
    'nominatingTeamId': 0,
    'overallPickNumber': 40,
    'playerId': 4258173,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 12,
    'teamId': 9,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 41,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 41,
    'playerId': 16737,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 13,
    'teamId': 15,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 42,
    'keeper': False,
    'lineupSlotId': 6,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 42,
    'playerId': 4430027,
    'reservedForKeeper': False,
    'roundId': 3,
    'roundPickNumber': 14,
    'teamId': 13,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 43,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 43,
    'playerId': 4697815,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 1,
    'teamId': 13,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 44,
    'keeper': False,
    'lineupSlotId': 23,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 44,
    'playerId': 4360438,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 2,
    'teamId': 15,
    'tradeLocked': False},
   {'autoDraftTypeId': 3,
    'bidAmount': 0,
    'id': 45,
    'keeper': False,
    'lineupSlotId': 23,
    'nominatingTeamId': 0,
    'overallPickNumber': 45,
    'playerId': 4047650,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 3,
    'teamId': 9,
    'tradeLocked': False},
   {'autoDraftTypeId': 1,
    'bidAmount': 0,
    'id': 46,
    'keeper': False,
    'lineupSlotId': 23,
    'nominatingTeamId': 0,
    'overallPickNumber': 46,
    'playerId': 4241478,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 4,
    'teamId': 12,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 47,
    'keeper': False,
    'lineupSlotId': 20,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 47,
    'playerId': 8439,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 5,
    'teamId': 17,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 48,
    'keeper': False,
    'lineupSlotId': 6,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 48,
    'playerId': 3116365,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 6,
    'teamId': 11,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 49,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 49,
    'playerId': 2977187,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 7,
    'teamId': 16,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 50,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 50,
    'playerId': 3915416,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 8,
    'teamId': 6,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 51,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 51,
    'playerId': 4567048,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 9,
    'teamId': 10,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 52,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 52,
    'playerId': 3042519,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 10,
    'teamId': 8,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 53,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 53,
    'playerId': 3116165,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 11,
    'teamId': 4,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 54,
    'keeper': False,
    'lineupSlotId': 4,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 54,
    'playerId': 4372016,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 12,
    'teamId': 1,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 55,
    'keeper': False,
    'lineupSlotId': 23,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 55,
    'playerId': 4239993,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 13,
    'teamId': 14,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 56,
    'keeper': False,
    'lineupSlotId': 6,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 56,
    'playerId': 3123076,
    'reservedForKeeper': False,
    'roundId': 4,
    'roundPickNumber': 14,
    'teamId': 3,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 57,
    'keeper': False,
    'lineupSlotId': 0,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 57,
    'playerId': 4432577,
    'reservedForKeeper': False,
    'roundId': 5,
    'roundPickNumber': 1,
    'teamId': 3,
    'tradeLocked': False},
   {'autoDraftTypeId': 0,
    'bidAmount': 0,
    'id': 58,
    'keeper': False,
    'lineupSlotId': 2,
    'memberId': '{REDACTED-ESPN-MEMBER-ID}',
    'nominatingTeamId': 0,
    'overallPickNumber': 58,
    'playerId': 3045147,
    'reservedForKeeper': False,
    'roundId': 5,
    'roundPickNumber': 2,
    'teamId': 14,

In [ ]:
df_draft = pd.DataFrame(draft['draftDetail']['picks'])
df_draft = df_draft.drop(columns=['bidAmount', 'keeper', 'nominatingTeamId', 'reservedForKeeper', 'tradeLocked'])
df_draft = df_draft.set_index(['playerId'])
df_draft

,autoDraftTypeId,id,lineupSlotId,memberId,overallPickNumber,roundId,roundPickNumber,teamId
playerId,,,,,,,,
3117251,0,1,2,{REDACTED-ESPN-MEMBER-ID},1,1,1,3
4241389,0,2,4,{REDACTED-ESPN-MEMBER-ID},2,1,2,14
3929630,0,3,2,{REDACTED-ESPN-MEMBER-ID},3,1,3,1
3918298,0,4,0,{REDACTED-ESPN-MEMBER-ID},4,1,4,4
4427366,3,5,2,NaN,5,1,5,8
...,...,...,...,...,...,...,...,...
4048244,3,220,20,NaN,220,16,10,8
4428209,1,221,20,NaN,221,16,11,4
15965,1,222,20,NaN,222,16,12,1
4362887,0,223,20,{REDACTED-ESPN-MEMBER-ID},223,16,13,14
3051738,0,224,20,{REDACTED-ESPN-MEMBER-ID},224,16,14,3

In [ ]:
save_to_data_raw()

In [ ]:

save_path = os.path.join(project_root, "data", "raw", "player_stats.csv")

# Make sure the folder exists
os.makedirs(os.path.dirname(save_path), exist_ok=True)

# Save the DataFrame
df_n.to_csv(save_path, index=False)
print(f"File saved to: {save_path}")

In [152]:
merged = df_players.merge(df_draft, on='playerId', how='outer')
merged = merged.set_index(['fullName', 'overallPickNumber'], append=True)
merged = merged.sort_values(by='overallPickNumber', ascending=True)
merged

,,,defaultPositionId,droppable,eligibleSlots,firstName,lastName,ownership,proTeamId,universeId,autoDraftTypeId,id,lineupSlotId,memberId,roundId,roundPickNumber,teamId
playerId,fullName,overallPickNumber,,,,,,,,,,,,,,,
3117251,Christian McCaffrey,1.0,2,True,"[2, 3, 23, 7, 20, 21]",Christian,McCaffrey,{'percentOwned': 60.00641522223298},25,2,0.0,1.0,2.0,{REDACTED-ESPN-MEMBER-ID},1.0,1.0,3.0
4241389,CeeDee Lamb,2.0,3,True,"[3, 4, 5, 23, 7, 20, 21]",CeeDee,Lamb,{'percentOwned': 87.96836947627831},6,2,0.0,2.0,4.0,{REDACTED-ESPN-MEMBER-ID},1.0,2.0,14.0
3929630,Saquon Barkley,3.0,2,True,"[2, 3, 23, 7, 20, 21]",Saquon,Barkley,{'percentOwned': 98.14805960827225},21,2,0.0,3.0,2.0,{REDACTED-ESPN-MEMBER-ID},1.0,3.0,1.0
3918298,Josh Allen,4.0,1,True,"[0, 7, 20, 21]",Josh,Allen,{'percentOwned': 98.16586356120428},2,1,0.0,4.0,0.0,{REDACTED-ESPN-MEMBER-ID},1.0,4.0,4.0
4427366,Breece Hall,5.0,2,True,"[2, 3, 23, 7, 20, 21]",Breece,Hall,{'percentOwned': 98.56056328310677},20,1,3.0,5.0,2.0,NaN,1.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5143915,Nick Whiteside II,NaN,12,True,"[12, 14, 15, 20, 21]",Nick,Whiteside II,{'percentOwned': 0.0033875338753387536},0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5144894,Trevor Nowaske,NaN,10,True,"[9, 11, 15, 20, 21]",Trevor,Nowaske,{'percentOwned': 0.07406930310446992},8,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5208436,Louis Rees-Zammit,NaN,2,True,"[25, 2, 3, 23, 7, 20, 21]",Louis,Rees-Zammit,{'percentOwned': 0.05416695162316264},30,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5208977,Qwan'tez Stiggers,NaN,12,True,"[25, 12, 14, 15, 20, 21]",Qwan'tez,Stiggers,{'percentOwned': 0.05758222402872337},20,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5216101,Dondrea Tillman,NaN,10,True,"[25, 9, 11, 15, 20, 21]",Dondrea,Tillman,{'percentOwned': 0.034223134839151265},7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
league = league.espn_request.get_league()

In [209]:
league

{'draftDetail': {'drafted': True, 'inProgress': False},
 'gameId': 1,
 'id': 780575,
 'members': [{'displayName': 'ESPNFAN7429418016',
   'firstName': 'Brynn',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McKendry',
   'notificationSettings': [{'enabled': True,
     'id': 'e41458de-6e51-368d-9dfd-650ee8c254d8',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '751e7960-6b93-31b2-8c89-b12d8d15a5e4',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': '46b9c5db-9d1b-3b39-a243-b60c48a57799',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '4b806695-7764-3686-8a86-4d002805e1e3',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '49498421-7077-3948-944b-9180973769f5',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': '2896565a-cf2e-3be0-93ca-d4a53c918e11',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '19aac3ff-b90d-3043-ad1c-c337e72082a7',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': '9aa1e68f-caf2-3910-88e0-cbc0a0301dae',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '47143c82-5dd8-3c50-980a-b5a11e236197',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': '928c09ec-6881-3817-8250-44accc3357b2',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': 'aaf4b289-390d-368c-9c94-1e0aadf3a1c9',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '538ce213-abde-3fb2-8645-b8f1b016be5a',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '3607b76f-d24e-3162-b802-a9aab5f6246d',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'justin365',
   'firstName': 'Justin',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McKendry',
   'notificationSettings': [{'enabled': True,
     'id': '24427f74-a7bc-3443-bbf4-440922ec5d5c',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '704f3aa0-bc50-3e7e-9b67-20aebd8d2bfe',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': '6846b8a2-bd1f-340c-af9a-43e35e771ed1',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '7b544c33-869e-3044-8014-653ce91c8d56',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '19def39c-da35-3503-9d74-2d5eb726eccc',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': 'a76ff7b4-7d07-3ad1-8fcf-31314b09344e',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '27b38b11-25ca-36d6-9b54-23a46934ba22',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': '021bf069-e65c-32d1-a2dd-da4f36b8983a',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': 'b05edff9-28b9-3fb3-b0ee-d61592435ef7',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': '8d643e8b-338d-3edc-8cb3-0b1baa283c73',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '4a6f4ac4-e8c0-373d-98fc-41d80ffc3686',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '19af73de-8cb8-3874-99a6-f0fc4b93df79',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '48d48bae-b395-3315-8207-1727b5ebc6a2',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'ESPNFAN8026643343',
   'firstName': 'Joe',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'Mcdowell',
   'notificationSettings': [{'enabled': True,
     'id': '03a902fb-86e9-3ae3-8c76-2da56d31747b',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '6b568b1b-cd3d-3a44-bb60-51d7899be9e9',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': 'c4c420e8-d41c-3020-8efc-0aca78bdf927',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '6293e2b3-ddd9-3498-ac69-a1ea2c2761cf',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '2b5e6853-16ce-34fd-acb0-db229c14a0a6',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': '3f77828a-6700-3371-89f9-4c64270ff94e',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': 'f7ce2a59-d672-312f-b04f-dc4e63f0622b',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': '43c55bfc-5138-3379-8d79-a2d96bc5636b',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': 'c24f759d-7f7c-38b5-bf08-978ed0a6337b',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': '4cef1cb1-ba19-3374-a4ea-29ef3787cd4d',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '326f6a51-8494-3ddc-abbb-f619027e0aca',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': 'f29c6916-cd52-3d9b-87d8-c1c6ec3127a1',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '4165edd3-ba1f-3df6-b0a8-8fecee43a3dd',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'Kelly McKendry',
   'firstName': 'Kelly',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McKendry',
   'notificationSettings': [{'enabled': True,
     'id': '2207ce84-b62c-3881-b79f-0a9f3288a979',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': 'ce78bdf0-ed88-380a-87d6-5900b9866b44',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': '08031ba0-7f5c-356b-9feb-53ae0f306340',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '1b858eb0-b85d-3fd1-96c2-5a30544c8ce9',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '3a3b7563-b17c-3b27-8ac9-14c76f2ad32d',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': '95548c8d-f8fd-3a73-83b9-5c1cbc76c5d5',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': 'fa1a5d56-ee16-3ca3-961b-fd1d6407e24a',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': '7dacb8ed-0610-36b3-8ca0-db45a515f9b6',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '414c2a62-153d-3910-85a2-5f75d0125a8f',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': 'afe6e785-aeab-3ea3-b87e-fca32d77d3db',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '95e0d8da-5489-36e7-8020-94798b0d5f17',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '3e87a225-0284-3cc1-82a7-cae9ea18547e',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '40a3f26b-77e8-3b54-b719-9497e894d13e',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'tlrowe00',
   'firstName': 'thomas',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'rowe',
   'notificationSettings': [{'enabled': True,
     'id': 'e34e7875-175f-3f28-8c9e-261266fadca4',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '8c0a84c7-550f-3836-8dcc-930af45f7dff',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': 'f28bc225-3450-3941-baac-27f8a891e88e',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '24cff79b-cb3b-3c0c-82a6-afde738ce776',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': 'dbf2e8f8-7b76-3398-b543-fdf9c2a4eb6d',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': 'cbaf530b-5b45-3123-874a-5921e8fe06fc',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '6e2c4e25-fd31-37f7-8b24-9fd875c368a4',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': 'd6c7ca24-31fb-322f-bb41-5cdbd541cce0',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '9bfcd66f-4cd4-308b-8e3e-2c4df866f257',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': 'd15e1b45-3026-382d-8d1b-852e1d19777a',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '3896a844-fc97-39fd-abde-bd19739c1306',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '1310a7dd-71a2-3d43-b504-c519e6968bc8',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '6c0f124a-c883-393c-b539-a69762553343',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'msmckendry',
   'firstName': 'Sam',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McKendry',
   'notificationSettings': [{'enabled': True,
     'id': '0e2ca2ef-0d3d-35bc-b230-4ed78b8d64b7',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '6500d495-26ea-3a7c-a5f0-d97fe90d1220',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': 'fda898ea-b05e-3796-8a81-dd534c7da571',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '2c72fe55-6f62-3803-8b6e-f116fdef9893',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': 'b8accda1-5b25-3ccb-86d0-7f4d998d8d96',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': '8e4579f1-5c72-3f0e-9714-8703fc795a06',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': 'd9031de3-7c0c-3479-99af-2cf446662835',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': '839013e9-a2c0-353d-9c12-6255d18cd77b',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '15b4b6b1-e604-3295-923d-340665b7e6e3',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': '488b7c81-3acb-365f-8281-01c4b25371e6',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': 'fa0a5b87-476f-3049-a345-bd97b5d686d1',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '8f4cfba6-c8ef-3d49-b29c-a7e37c189819',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '83cb8240-8571-3f2d-b21f-38cb4bc0998c',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'dstarrmcd83',
   'firstName': 'Dana',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McDowell',
   'notificationSettings': [{'enabled': True,
     'id': 'd8981804-b7f3-373d-b4e9-5f5569b03833',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '9803c4f2-2a4a-304f-ae82-fc5c95ca18cc',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': '5b9e58bd-50d8-3dac-86a4-2e5a40d3a8d8',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': 'fc9f4469-00bf-3956-8c5c-c257342149e7',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '29e634e9-3601-3fcb-8bfc-a6d381e335bc',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': 'bdf73097-2ebc-3d14-ba96-13a81cce1e9a',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '65328bf3-b7e0-36bc-9b1f-353f170f6e95',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': 'f199262b-e052-3914-a421-53d8039c96da',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': 'cfe2022e-87dc-3413-85b8-06b478e2e247',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': 'acaefaab-ce5e-37e7-95a3-7d222346cde7',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '0e1a2ed5-ae93-3aef-9d95-b0329c3b7d2d',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '27865a3a-c844-3b40-8eb7-fc1d65712975',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': 'b9a0eed4-01b7-30f1-9bbb-7eb14cc83a55',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'pmcdowski',
   'firstName': 'Paul',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McDowell',
   'notificationSettings': [{'enabled': True,
     'id': 'fe4ea35e-68f4-3571-b918-c400ba5cc183',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '5e594f8d-ff60-3d95-8e7c-1c07df492df7',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': '8bea3ef3-820f-3774-860f-1363c9c390af',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '13ce84c5-8cb7-3dc9-ab92-54b2237934ab',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': 'acadd462-0a2e-3544-9277-4730410ec6a4',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': 'd1d9077d-c901-39d2-97e6-a2297aaac286',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '80352bed-a71d-39b0-9276-1d673492a7a9',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': '2dc0b99d-0c22-36cf-a331-d46aa636f316',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': 'c4d85582-96ab-3d30-97df-8400dff6cf89',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': 'd0bc48eb-38ba-3ec3-912c-cb43fa3926b2',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': 'a4281b9a-5588-330f-a4c7-775e6dadc2af',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '40ed4065-e4f1-3732-b6c9-10df80c07585',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': 'c03a2c50-6a52-33d7-b84f-3cce50e60d93',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'Eagles1721',
   'firstName': 'Ryan',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McDowell',
   'notificationSettings': [{'enabled': True,
     'id': '4e6f90a5-ae9d-3dd3-935e-bbbce017c140',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': 'd94bcd46-3dab-3e3c-acb9-fc1ef10b4776',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': 'df664bfa-da4d-3ebf-a28e-d3aceecd0de3',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '99dceaa3-f768-3871-b066-6bbaf607298f',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '0096d234-f459-3349-aa67-149e94f7d6ac',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': '30ba1aef-dee8-3181-a9fc-fb122e1c3804',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': 'efc0d989-70db-3daf-a281-afe1da0f7dce',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': '63a2e626-4dfe-310b-b757-ccc9cdc7cf06',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '5969e8dc-520a-380d-8ec3-9213d5d70bf6',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': '7641c1c7-cf85-3c60-8f69-9161d59bb143',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '51e260b0-6bde-3f45-8d4d-345bee57a18f',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': '130dc9ee-e263-3f63-ac46-b5703ef3aa88',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '9fd96fae-0749-3752-adbd-9e1383785b99',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'Kristaann88@aol.com',
   'firstName': 'Krista',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'Carlson',
   'notificationSettings': [{'enabled': True,
     'id': '5f6a22c2-e0c4-384f-9e38-59a7a5c6450d',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '5845f070-4f9d-33ce-af86-5a771e99f314',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': 'c1e537ca-24fd-3657-a24e-0428177f2e2a',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': 'd3c7bca3-fc19-32d1-be93-541c8d36288b',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': 'a9461117-57b0-3ac4-806a-d363296d50c8',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': '63dde916-5bd0-3106-b7bd-f462ba2e3e8d',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '19e0c421-d9d7-3be9-a81c-2865368cae4e',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': 'e5247468-803d-30f1-aadc-bac73c28f69f',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '8d3c9d4e-dd86-30e9-87b8-f8367663d4d8',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': 'c1533904-77f1-3fd2-8508-ca9d3a4bdc0a',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '4848103a-7d95-3a83-b40b-3ba9f79c5417',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': 'e52b7966-6f22-3a16-a13f-2da0d3ed48dc',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '6d29e697-85a8-3ec5-b861-d34d027cac79',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'justin6699815',
   'firstName': 'Justin',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McKendry',
   'notificationSettings': [{'enabled': True,
     'id': 'd5a8dc09-61cf-301e-ac04-624e6c311f59',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': 'b7c58251-7f3c-3fa2-a590-aafff8921284',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': '2e089a20-8b62-3960-9c5b-1c9dac068a35',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '5bb74b86-9520-3037-bd2c-5f53408cee6c',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '46879a0a-df8d-3c2c-a154-2104d4ef149e',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': 'bc83e1db-b1af-33e6-9f19-8794b78d377b',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': 'a55e640c-760d-3d7e-9c59-381bddf256fe',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': 'fec5b6a2-05a0-3ba8-974c-d337f819b6a5',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '63ea2250-afff-3392-bb47-0030b7f1ad0c',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': 'a0700216-ddd5-3fdf-9623-36251623a53b',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '7f2b31ce-f3a9-33ed-aaf2-41e73536873a',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': 'c78cbdec-3f05-33c0-9aca-aeb348a8ba5b',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '4d0fa874-147d-3a37-b3aa-ae1b17b810c6',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'ThunderLuke',
   'firstName': 'Luke',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McKendry',
   'notificationSettings': [{'enabled': True,
     'id': '4b2c64a9-1846-39e6-88fb-7b8efde39e3f',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': '4be59c60-61fc-3933-8401-4a24948144e1',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': 'f27c9972-6fa3-35db-9588-369903586888',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': 'ee1892a5-a25d-3acd-9a86-892478063866',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '94b4aa5b-b3d5-36bd-a053-d97baa453bd4',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': 'f62dcebb-4364-3c68-9255-1a7153c3d315',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '9598d516-0c0c-3d84-bff2-0eb297e8caf9',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': 'a9c9b797-5b02-3c43-82c6-476416adc837',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': '738b6091-bad5-360f-bce4-a901b0fbbb4f',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': '83e8afe9-d937-3929-a497-1a550675f64a',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': '6fbaf9f1-6b13-3146-acac-845a1755e6c1',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': 'ffed605d-5bfd-3eb7-931a-f15594f9db11',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': 'bc733ba8-2d77-3c15-9b7d-54e2eb97917e',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'Kristin McDowell',
   'firstName': 'Kristin',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McDowell',
   'notificationSettings': [{'enabled': True,
     'id': '590d01e4-a0c7-3922-ab03-432177cb2b26',
     'type': 'TEAM_PLAYER_INJURY'},
    {'enabled': True,
     'id': 'bd5c048f-506c-3dc5-9c31-08bdcda47cfa',
     'type': 'TEAM_PLAYER_AVAILABILITY'},
    {'enabled': True,
     'id': '155462e8-036d-300e-8a8a-15d6346322ad',
     'type': 'TEAM_PLAYER_NEWS'},
    {'enabled': True,
     'id': '6a1a32a2-c525-3edc-8470-830145f47000',
     'type': 'TEAM_PLAYER_STARTBENCH'},
    {'enabled': True,
     'id': '4080aabb-e4ff-3f54-b953-eb4db8fdb998',
     'type': 'TEAM_TRADE_OFFER'},
    {'enabled': True,
     'id': 'c75ee7db-f266-31c8-a905-bf5db91c864b',
     'type': 'DRAFT'},
    {'enabled': True,
     'id': '263a706a-3172-3e0c-a4f3-fc9506eea4d6',
     'type': 'TEAM_MATCHUP_SCORE'},
    {'enabled': True,
     'id': 'a70d9663-f689-3cab-a8dc-c4a5fbdd5edc',
     'type': 'KEY_PLAY'},
    {'enabled': True,
     'id': 'bb092e84-b8eb-35c8-af90-7df21c777adf',
     'type': 'REDZONE'},
    {'enabled': True,
     'id': 'd2de8d0d-0ad6-319a-bf81-f7d18cc90a9c',
     'type': 'ADD_DROP'},
    {'enabled': True,
     'id': 'f9073293-6a34-3386-bffa-96344fd1f16a',
     'type': 'WEEKLY_RECAP'},
    {'enabled': True,
     'id': 'b5e9b8ad-c2aa-3d8d-a266-e821df626b7f',
     'type': 'WAIVERS'},
    {'enabled': True,
     'id': '7cd40fa2-8258-3b21-a756-0fde737edaef',
     'type': 'CELEBRATION_SHARE'}]},
  {'displayName': 'Old Salt 215',
   'firstName': 'Jason',
   'id': '{REDACTED-ESPN-MEMBER-ID}',
   'lastName': 'McKendry',
   'notificationSettings': [{'enabled': True,
     'id': '2e3581c3-a8d7-3463-a130-a11f7b2c3048',
     'type': 'TEAM_PLAYER_INJURY'},

In [206]:
schedule = league.espn_request.get_pro_schedule()

In [207]:
schedule

{'display': True,
 'settings': {'defaultDraftPosition': 170,
  'draftLobbyMinimumLeagueCount': 3,
  'gameNotificationSettings': {'availabilityNotificationsEnabled': True,
   'draftNotificationsEnabled': True,
   'injuryNotificationsEnabled': True,
   'lineupNotificationsEnabled': False,
   'positionEligibilityNotificationsEnabled': False,
   'rosterNewsNotificationsEnabled': True,
   'startBenchNotificationsEnabled': True,
   'tradeNotificationsEnabled': True},
  'gated': False,
  'playerOwnershipSettings': {'firstGameDate': 1725534034617,
   'lastGameDate': 1736078400725,
   'startDate': 1712559600000},
  'proTeams': [{'abbrev': 'Ind',
    'byeWeek': 14,
    'id': 11,
    'location': 'Indianapolis',
    'name': 'Colts',
    'proGamesByScoringPeriod': {'1': [{'awayProTeamId': 34,
       'date': 1725814800000,
       'homeProTeamId': 11,
       'id': 401671861,
       'scoringPeriodId': 1,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '2': [{'awayProTeamId': 11,
       'date': 1726419600000,
       'homeProTeamId': 9,
       'id': 401671723,
       'scoringPeriodId': 2,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '3': [{'awayProTeamId': 3,
       'date': 1727024400000,
       'homeProTeamId': 11,
       'id': 401671865,
       'scoringPeriodId': 3,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '4': [{'awayProTeamId': 23,
       'date': 1727629200000,
       'homeProTeamId': 11,
       'id': 401671867,
       'scoringPeriodId': 4,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '5': [{'awayProTeamId': 11,
       'date': 1728234000000,
       'homeProTeamId': 30,
       'id': 401671633,
       'scoringPeriodId': 5,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '6': [{'awayProTeamId': 11,
       'date': 1728838800000,
       'homeProTeamId': 10,
       'id': 401671820,
       'scoringPeriodId': 6,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '7': [{'awayProTeamId': 15,
       'date': 1729443600000,
       'homeProTeamId': 11,
       'id': 401671864,
       'scoringPeriodId': 7,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '8': [{'awayProTeamId': 11,
       'date': 1730048400000,
       'homeProTeamId': 34,
       'id': 401671856,
       'scoringPeriodId': 8,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '9': [{'awayProTeamId': 11,
       'date': 1730683200000,
       'homeProTeamId': 16,
       'id': 401671647,
       'scoringPeriodId': 9,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '10': [{'awayProTeamId': 2,
       'date': 1731261600000,
       'homeProTeamId': 11,
       'id': 401671863,
       'scoringPeriodId': 10,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '11': [{'awayProTeamId': 11,
       'date': 1731866400000,
       'homeProTeamId': 20,
       'id': 401671782,
       'scoringPeriodId': 11,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '12': [{'awayProTeamId': 8,
       'date': 1732471200000,
       'homeProTeamId': 11,
       'id': 401671866,
       'scoringPeriodId': 12,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '13': [{'awayProTeamId': 11,
       'date': 1733076000000,
       'homeProTeamId': 17,
       'id': 401671620,
       'scoringPeriodId': 13,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '15': [{'awayProTeamId': 11,
       'date': 1734297900000,
       'homeProTeamId': 7,
       'id': 401671669,
       'scoringPeriodId': 15,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '16': [{'awayProTeamId': 10,
       'date': 1734890400000,
       'homeProTeamId': 11,
       'id': 401671862,
       'scoringPeriodId': 16,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '17': [{'awayProTeamId': 11,
       'date': 1735495200000,
       'homeProTeamId': 19,
       'id': 401671846,
       'scoringPeriodId': 17,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '18': [{'awayProTeamId': 30,
       'date': 1736100000000,
       'homeProTeamId': 11,
       'id': 401671837,
       'scoringPeriodId': 18,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}]},
    'teamPlayersByPosition': {'16': -16011, '14': -14011, '15': -15011},
    'universeId': 1},
   {'abbrev': 'KC',
    'byeWeek': 6,
    'id': 12,
    'location': 'Kansas City',
    'name': 'Chiefs',
    'proGamesByScoringPeriod': {'1': [{'awayProTeamId': 33,
       'date': 1725582000000,
       'homeProTeamId': 12,
       'id': 401671789,
       'scoringPeriodId': 1,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '2': [{'awayProTeamId': 4,
       'date': 1726431900000,
       'homeProTeamId': 12,
       'id': 401671670,
       'scoringPeriodId': 2,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '3': [{'awayProTeamId': 12,
       'date': 1727050800000,
       'homeProTeamId': 1,
       'id': 401671793,
       'scoringPeriodId': 3,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '4': [{'awayProTeamId': 12,
       'date': 1727641500000,
       'homeProTeamId': 24,
       'id': 401671674,
       'scoringPeriodId': 4,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '5': [{'awayProTeamId': 18,
       'date': 1728346500000,
       'homeProTeamId': 12,
       'id': 401671687,
       'scoringPeriodId': 5,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '7': [{'awayProTeamId': 12,
       'date': 1729455900000,
       'homeProTeamId': 25,
       'id': 401671777,
       'scoringPeriodId': 7,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '8': [{'awayProTeamId': 12,
       'date': 1730060700000,
       'homeProTeamId': 13,
       'id': 401671671,
       'scoringPeriodId': 8,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '9': [{'awayProTeamId': 27,
       'date': 1730769300000,
       'homeProTeamId': 12,
       'id': 401671688,
       'scoringPeriodId': 9,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '10': [{'awayProTeamId': 7,
       'date': 1731261600000,
       'homeProTeamId': 12,
       'id': 401671637,
       'scoringPeriodId': 10,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '11': [{'awayProTeamId': 12,
       'date': 1731878700000,
       'homeProTeamId': 2,
       'id': 401671665,
       'scoringPeriodId': 11,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '12': [{'awayProTeamId': 12,
       'date': 1732471200000,
       'homeProTeamId': 29,
       'id': 401671651,
       'scoringPeriodId': 12,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '13': [{'awayProTeamId': 13,
       'date': 1732910400000,
       'homeProTeamId': 12,
       'id': 401671806,
       'scoringPeriodId': 13,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '14': [{'awayProTeamId': 24,
       'date': 1733707200000,
       'homeProTeamId': 12,
       'id': 401671788,
       'scoringPeriodId': 14,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '15': [{'awayProTeamId': 12,
       'date': 1734285600000,
       'homeProTeamId': 5,
       'id': 401671854,
       'scoringPeriodId': 15,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '16': [{'awayProTeamId': 34,
       'date': 1734804000000,
       'homeProTeamId': 12,
       'id': 401671780,
       'scoringPeriodId': 16,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '17': [{'awayProTeamId': 12,
       'date': 1735149600000,
       'homeProTeamId': 23,
       'id': 401671799,
       'scoringPeriodId': 17,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '18': [{'awayProTeamId': 12,
       'date': 1736112300000,
       'homeProTeamId': 7,
       'id': 401671838,
       'scoringPeriodId': 18,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}]},
    'teamPlayersByPosition': {'16': -16012, '14': -14012, '15': -15012},
    'universeId': 1},
   {'abbrev': 'LV',
    'byeWeek': 10,
    'id': 13,
    'location': 'Las Vegas',
    'name': 'Raiders',
    'proGamesByScoringPeriod': {'1': [{'awayProTeamId': 13,
       'date': 1725825900000,
       'homeProTeamId': 24,
       'id': 401671659,
       'scoringPeriodId': 1,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '2': [{'awayProTeamId': 13,
       'date': 1726419600000,
       'homeProTeamId': 33,
       'id': 401671624,
       'scoringPeriodId': 2,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '3': [{'awayProTeamId': 29,
       'date': 1727035500000,
       'homeProTeamId': 13,
       'id': 401671658,
       'scoringPeriodId': 3,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '4': [{'awayProTeamId': 5,
       'date': 1727641500000,
       'homeProTeamId': 13,
       'id': 401671672,
       'scoringPeriodId': 4,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '5': [{'awayProTeamId': 13,
       'date': 1728245100000,
       'homeProTeamId': 7,
       'id': 401671747,
       'scoringPeriodId': 5,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '6': [{'awayProTeamId': 23,
       'date': 1728849900000,
       'homeProTeamId': 13,
       'id': 401671657,
       'scoringPeriodId': 6,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '7': [{'awayProTeamId': 13,
       'date': 1729454700000,
       'homeProTeamId': 14,
       'id': 401671663,
       'scoringPeriodId': 7,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '8': [{'awayProTeamId': 12,
       'date': 1730060700000,
       'homeProTeamId': 13,
       'id': 401671671,
       'scoringPeriodId': 8,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '9': [{'awayProTeamId': 13,
       'date': 1730656800000,
       'homeProTeamId': 4,
       'id': 401671704,
       'scoringPeriodId': 9,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '11': [{'awayProTeamId': 13,
       'date': 1731866400000,
       'homeProTeamId': 15,
       'id': 401671851,
       'scoringPeriodId': 11,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '12': [{'awayProTeamId': 7,
       'date': 1732482300000,
       'homeProTeamId': 13,
       'id': 401671656,
       'scoringPeriodId': 12,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '13': [{'awayProTeamId': 13,
       'date': 1732910400000,
       'homeProTeamId': 12,
       'id': 401671806,
       'scoringPeriodId': 13,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '14': [{'awayProTeamId': 13,
       'date': 1733680800000,
       'homeProTeamId': 27,
       'id': 401671654,
       'scoringPeriodId': 14,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '15': [{'awayProTeamId': 1,
       'date': 1734399000000,
       'homeProTeamId': 13,
       'id': 401671697,
       'scoringPeriodId': 15,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '16': [{'awayProTeamId': 30,
       'date': 1734902700000,
       'homeProTeamId': 13,
       'id': 401671673,
       'scoringPeriodId': 16,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '17': [{'awayProTeamId': 13,
       'date': 1735495200000,
       'homeProTeamId': 18,
       'id': 401671738,
       'scoringPeriodId': 17,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '18': [{'awayProTeamId': 24,
       'date': 1736112300000,
       'homeProTeamId': 13,
       'id': 401671839,
       'scoringPeriodId': 18,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}]},
    'teamPlayersByPosition': {'16': -16013, '14': -14013, '15': -15013},
    'universeId': 1},
   {'abbrev': 'LAR',
    'byeWeek': 6,
    'id': 14,
    'location': 'Los Angeles',
    'name': 'Rams',
    'proGamesByScoringPeriod': {'1': [{'awayProTeamId': 14,
       'date': 1725841200000,
       'homeProTeamId': 8,
       'id': 401671792,
       'scoringPeriodId': 1,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '2': [{'awayProTeamId': 14,
       'date': 1726430700000,
       'homeProTeamId': 22,
       'id': 401671754,
       'scoringPeriodId': 2,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '3': [{'awayProTeamId': 25,
       'date': 1727036700000,
       'homeProTeamId': 14,
       'id': 401671772,
       'scoringPeriodId': 3,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '4': [{'awayProTeamId': 14,
       'date': 1727629200000,
       'homeProTeamId': 3,
       'id': 401671871,
       'scoringPeriodId': 4,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '5': [{'awayProTeamId': 9,
       'date': 1728246300000,
       'homeProTeamId': 14,
       'id': 401671679,
       'scoringPeriodId': 5,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '7': [{'awayProTeamId': 13,
       'date': 1729454700000,
       'homeProTeamId': 14,
       'id': 401671663,
       'scoringPeriodId': 7,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '8': [{'awayProTeamId': 16,
       'date': 1729815300000,
       'homeProTeamId': 14,
       'id': 401671817,
       'scoringPeriodId': 8,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '9': [{'awayProTeamId': 14,
       'date': 1730669100000,
       'homeProTeamId': 26,
       'id': 401671776,
       'scoringPeriodId': 9,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '10': [{'awayProTeamId': 15,
       'date': 1731374100000,
       'homeProTeamId': 14,
       'id': 401671693,
       'scoringPeriodId': 10,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '11': [{'awayProTeamId': 14,
       'date': 1731866400000,
       'homeProTeamId': 17,
       'id': 401671701,
       'scoringPeriodId': 11,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '12': [{'awayProTeamId': 21,
       'date': 1732497600000,
       'homeProTeamId': 14,
       'id': 401671794,
       'scoringPeriodId': 12,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '13': [{'awayProTeamId': 14,
       'date': 1733087100000,
       'homeProTeamId': 18,
       'id': 401671753,
       'scoringPeriodId': 13,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '14': [{'awayProTeamId': 2,
       'date': 1733693100000,
       'homeProTeamId': 14,
       'id': 401671773,
       'scoringPeriodId': 14,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '15': [{'awayProTeamId': 14,
       'date': 1734052500000,
       'homeProTeamId': 25,
       'id': 401671818,
       'scoringPeriodId': 15,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '16': [{'awayProTeamId': 14,
       'date': 1734890400000,
       'homeProTeamId': 20,
       'id': 401671621,
       'scoringPeriodId': 16,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '17': [{'awayProTeamId': 22,
       'date': 1735434000000,
       'homeProTeamId': 14,
       'id': 401671829,
       'scoringPeriodId': 17,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '18': [{'awayProTeamId': 26,
       'date': 1736112300000,
       'homeProTeamId': 14,
       'id': 401671830,
       'scoringPeriodId': 18,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}]},
    'teamPlayersByPosition': {'16': -16014, '14': -14014, '15': -15014},
    'universeId': 2},
   {'abbrev': 'Mia',
    'byeWeek': 6,
    'id': 15,
    'location': 'Miami',
    'name': 'Dolphins',
    'proGamesByScoringPeriod': {'1': [{'awayProTeamId': 30,
       'date': 1725814800000,
       'homeProTeamId': 15,
       'id': 401671849,
       'scoringPeriodId': 1,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '2': [{'awayProTeamId': 2,
       'date': 1726186500000,
       'homeProTeamId': 15,
       'id': 401671807,
       'scoringPeriodId': 2,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '3': [{'awayProTeamId': 15,
       'date': 1727035500000,
       'homeProTeamId': 26,
       'id': 401671662,
       'scoringPeriodId': 3,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '4': [{'awayProTeamId': 10,
       'date': 1727739000000,
       'homeProTeamId': 15,
       'id': 401671683,
       'scoringPeriodId': 4,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '5': [{'awayProTeamId': 15,
       'date': 1728234000000,
       'homeProTeamId': 17,
       'id': 401671700,
       'scoringPeriodId': 5,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '7': [{'awayProTeamId': 15,
       'date': 1729443600000,
       'homeProTeamId': 11,
       'id': 401671864,
       'scoringPeriodId': 7,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '8': [{'awayProTeamId': 22,
       'date': 1730048400000,
       'homeProTeamId': 15,
       'id': 401671850,
       'scoringPeriodId': 8,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '9': [{'awayProTeamId': 15,
       'date': 1730656800000,
       'homeProTeamId': 2,
       'id': 401671493,
       'scoringPeriodId': 9,
       'startTimeTBD': False,
       'statsOfficial': True,
       'validForLocking': True}],
     '10': [{'awayProTeamId': 15,
       'date': 1731374100000,
       'homeProTeamId': 14,
       'id': 401671693,
       'scoringPeriodId': 10,
       'startTimeTBD': False,

In [204]:
df_schedule = pd.DataFrame(schedule['settings']['proTeams'])
df_schedule

,abbrev,byeWeek,id,location,name,proGamesByScoringPeriod,teamPlayersByPosition,universeId
0,Ind,14,11,Indianapolis,Colts,"{'1': [{'awayProTeamId': 34, 'date': 172581480...","{'16': -16011, '14': -14011, '15': -15011}",1
1,KC,6,12,Kansas City,Chiefs,"{'1': [{'awayProTeamId': 33, 'date': 172558200...","{'16': -16012, '14': -14012, '15': -15012}",1
2,LV,10,13,Las Vegas,Raiders,"{'1': [{'awayProTeamId': 13, 'date': 172582590...","{'16': -16013, '14': -14013, '15': -15013}",1
3,LAR,6,14,Los Angeles,Rams,"{'1': [{'awayProTeamId': 14, 'date': 172584120...","{'16': -16014, '14': -14014, '15': -15014}",2
4,Mia,6,15,Miami,Dolphins,"{'1': [{'awayProTeamId': 30, 'date': 172581480...","{'16': -16015, '14': -14015, '15': -15015}",1
5,Min,6,16,Minnesota,Vikings,"{'1': [{'awayProTeamId': 16, 'date': 172581480...","{'16': -16016, '14': -14016, '15': -15016}",2
6,NE,14,17,New England,Patriots,"{'1': [{'awayProTeamId': 17, 'date': 172581480...","{'16': -16017, '14': -14017, '15': -15017}",1
7,NO,12,18,New Orleans,Saints,"{'1': [{'awayProTeamId': 29, 'date': 172581480...","{'16': -16018, '14': -14018, '15': -15018}",2
8,NYG,11,19,New York,Giants,"{'1': [{'awayProTeamId': 16, 'date': 172581480...","{'16': -16019, '14': -14019, '15': -15019}",2
9,NYJ,12,20,New York,Jets,"{'1': [{'awayProTeamId': 20, 'date': 172592730...","{'16': -16020, '14': -14020, '15': -15020}",1
10,Phi,5,21,Philadelphia,Eagles,"{'1': [{'awayProTeamId': 9, 'date': 1725668100...","{'16': -16021, '14': -14021, '15': -15021}",2
11,Ari,11,22,Arizona,Cardinals,"{'1': [{'awayProTeamId': 22, 'date': 172581480...","{'16': -16022, '14': -14022, '15': -15022}",2
12,Pit,9,23,Pittsburgh,Steelers,"{'1': [{'awayProTeamId': 23, 'date': 172581480...","{'16': -16023, '14': -14023, '15': -15023}",1
13,LAC,5,24,Los Angeles,Chargers,"{'1': [{'awayProTeamId': 13, 'date': 172582590...","{'16': -16024, '14': -14024, '15': -15024}",1
14,SF,9,25,San Francisco,49ers,"{'1': [{'awayProTeamId': 20, 'date': 172592730...","{'16': -16025, '14': -14025, '15': -15025}",2
15,Sea,10,26,Seattle,Seahawks,"{'1': [{'awayProTeamId': 7, 'date': 1725825900...","{'16': -16026, '14': -14026, '15': -15026}",2
16,TB,11,27,Tampa Bay,Buccaneers,"{'1': [{'awayProTeamId': 28, 'date': 172582710...","{'16': -16027, '14': -14027, '15': -15027}",2
17,Wsh,14,28,Washington,Commanders,"{'1': [{'awayProTeamId': 28, 'date': 172582710...","{'16': -16028, '14': -14028, '15': -15028}",2
18,Car,11,29,Carolina,Panthers,"{'1': [{'awayProTeamId': 29, 'date': 172581480...","{'16': -16029, '14': -14029, '15': -15029}",2
19,Jax,12,30,Jacksonville,Jaguars,"{'1': [{'awayProTeamId': 30, 'date': 172581480...","{'16': -16030, '14': -14030, '15': -15030}",1
20,Bal,14,33,Baltimore,Ravens,"{'1': [{'awayProTeamId': 33, 'date': 172558200...","{'16': -16033, '14': -14033, '15': -15033}",1
21,Hou,14,34,Houston,Texans,"{'1': [{'awayProTeamId': 34, 'date': 172581480...","{'16': -16034, '14': -14034, '15': -15034}",1
22,FA,0,0,,FA,{},NaN,0
23,Atl,12,1,Atlanta,Falcons,"{'1': [{'awayProTeamId': 23, 'date': 172581480...","{'16': -16001, '14': -14001, '15': -15001}",2
24,Buf,12,2,Buffalo,Bills,"{'1': [{'awayProTeamId': 22, 'date': 172581480...","{'16': -16002, '14': -14002, '15': -15002}",1
25,Chi,7,3,Chicago,Bears,"{'1': [{'awayProTeamId': 10, 'date': 172581480...","{'16': -16003, '14': -14003, '15': -15003}",2
26,Cin,12,4,Cincinnati,Bengals,"{'1': [{'awayProTeamId': 17, 'date': 172581480...","{'16': -16004, '14': -14004, '15': -15004}",1
27,Cle,10,5,Cleveland,Browns,"{'1': [{'awayProTeamId': 6, 'date': 1725827100...","{'16': -16005, '14': -14005, '15': -15005}",1
28,Dal,7,6,Dallas,Cowboys,"{'1': [{'awayProTeamId': 6, 'date': 1725827100...","{'16': -16006, '14': -14006, '15': -15006}",2
29,Den,14,7,Denver,Broncos,"{'1': [{'awayProTeamId': 7, 'date': 1725825900...","{'16': -16007, '14': -14007, '15': -15007}",1
30,Det,5,8,Detroit,Lions,"{'1': [{'awayProTeamId': 14, 'date': 172584120...","{'16': -16008, '14': -14008, '15': -15008}",2
31,GB,10,9,Green Bay,Packers,"{'1': [{'awayProTeamId': 9, 'date': 1725668100...","{'16': -16009, '14': -14009, '15': -15009}",2
32,Ten,5,10,Tennessee,Titans,"{'1': [{'awayProTeamId': 10, 'date': 172581480...","{'16': -16010, '14': -14010, '15': -15010}",1

In [198]:
df_schedule['games'] = df_schedule['proGamesByScoringPeriod'].apply(
    lambda d: [{'week': int(week), **game} for week, games in d.items() for game in games]
)
df_schedule

,abbrev,byeWeek,id,location,name,proGamesByScoringPeriod,teamPlayersByPosition,universeId,games
0,Ind,14,11,Indianapolis,Colts,"{'1': [{'awayProTeamId': 34, 'date': 172581480...","{'16': -16011, '14': -14011, '15': -15011}",1,"[{'week': 1, 'awayProTeamId': 34, 'date': 1725..."
1,KC,6,12,Kansas City,Chiefs,"{'1': [{'awayProTeamId': 33, 'date': 172558200...","{'16': -16012, '14': -14012, '15': -15012}",1,"[{'week': 1, 'awayProTeamId': 33, 'date': 1725..."
2,LV,10,13,Las Vegas,Raiders,"{'1': [{'awayProTeamId': 13, 'date': 172582590...","{'16': -16013, '14': -14013, '15': -15013}",1,"[{'week': 1, 'awayProTeamId': 13, 'date': 1725..."
3,LAR,6,14,Los Angeles,Rams,"{'1': [{'awayProTeamId': 14, 'date': 172584120...","{'16': -16014, '14': -14014, '15': -15014}",2,"[{'week': 1, 'awayProTeamId': 14, 'date': 1725..."
4,Mia,6,15,Miami,Dolphins,"{'1': [{'awayProTeamId': 30, 'date': 172581480...","{'16': -16015, '14': -14015, '15': -15015}",1,"[{'week': 1, 'awayProTeamId': 30, 'date': 1725..."
5,Min,6,16,Minnesota,Vikings,"{'1': [{'awayProTeamId': 16, 'date': 172581480...","{'16': -16016, '14': -14016, '15': -15016}",2,"[{'week': 1, 'awayProTeamId': 16, 'date': 1725..."
6,NE,14,17,New England,Patriots,"{'1': [{'awayProTeamId': 17, 'date': 172581480...","{'16': -16017, '14': -14017, '15': -15017}",1,"[{'week': 1, 'awayProTeamId': 17, 'date': 1725..."
7,NO,12,18,New Orleans,Saints,"{'1': [{'awayProTeamId': 29, 'date': 172581480...","{'16': -16018, '14': -14018, '15': -15018}",2,"[{'week': 1, 'awayProTeamId': 29, 'date': 1725..."
8,NYG,11,19,New York,Giants,"{'1': [{'awayProTeamId': 16, 'date': 172581480...","{'16': -16019, '14': -14019, '15': -15019}",2,"[{'week': 1, 'awayProTeamId': 16, 'date': 1725..."
9,NYJ,12,20,New York,Jets,"{'1': [{'awayProTeamId': 20, 'date': 172592730...","{'16': -16020, '14': -14020, '15': -15020}",1,"[{'week': 1, 'awayProTeamId': 20, 'date': 1725..."
10,Phi,5,21,Philadelphia,Eagles,"{'1': [{'awayProTeamId': 9, 'date': 1725668100...","{'16': -16021, '14': -14021, '15': -15021}",2,"[{'week': 1, 'awayProTeamId': 9, 'date': 17256..."
11,Ari,11,22,Arizona,Cardinals,"{'1': [{'awayProTeamId': 22, 'date': 172581480...","{'16': -16022, '14': -14022, '15': -15022}",2,"[{'week': 1, 'awayProTeamId': 22, 'date': 1725..."
12,Pit,9,23,Pittsburgh,Steelers,"{'1': [{'awayProTeamId': 23, 'date': 172581480...","{'16': -16023, '14': -14023, '15': -15023}",1,"[{'week': 1, 'awayProTeamId': 23, 'date': 1725..."
13,LAC,5,24,Los Angeles,Chargers,"{'1': [{'awayProTeamId': 13, 'date': 172582590...","{'16': -16024, '14': -14024, '15': -15024}",1,"[{'week': 1, 'awayProTeamId': 13, 'date': 1725..."
14,SF,9,25,San Francisco,49ers,"{'1': [{'awayProTeamId': 20, 'date': 172592730...","{'16': -16025, '14': -14025, '15': -15025}",2,"[{'week': 1, 'awayProTeamId': 20, 'date': 1725..."
15,Sea,10,26,Seattle,Seahawks,"{'1': [{'awayProTeamId': 7, 'date': 1725825900...","{'16': -16026, '14': -14026, '15': -15026}",2,"[{'week': 1, 'awayProTeamId': 7, 'date': 17258..."
16,TB,11,27,Tampa Bay,Buccaneers,"{'1': [{'awayProTeamId': 28, 'date': 172582710...","{'16': -16027, '14': -14027, '15': -15027}",2,"[{'week': 1, 'awayProTeamId': 28, 'date': 1725..."
17,Wsh,14,28,Washington,Commanders,"{'1': [{'awayProTeamId': 28, 'date': 172582710...","{'16': -16028, '14': -14028, '15': -15028}",2,"[{'week': 1, 'awayProTeamId': 28, 'date': 1725..."
18,Car,11,29,Carolina,Panthers,"{'1': [{'awayProTeamId': 29, 'date': 172581480...","{'16': -16029, '14': -14029, '15': -15029}",2,"[{'week': 1, 'awayProTeamId': 29, 'date': 1725..."
19,Jax,12,30,Jacksonville,Jaguars,"{'1': [{'awayProTeamId': 30, 'date': 172581480...","{'16': -16030, '14': -14030, '15': -15030}",1,"[{'week': 1, 'awayProTeamId': 30, 'date': 1725..."
20,Bal,14,33,Baltimore,Ravens,"{'1': [{'awayProTeamId': 33, 'date': 172558200...","{'16': -16033, '14': -14033, '15': -15033}",1,"[{'week': 1, 'awayProTeamId': 33, 'date': 1725..."
21,Hou,14,34,Houston,Texans,"{'1': [{'awayProTeamId': 34, 'date': 172581480...","{'16': -16034, '14': -14034, '15': -15034}",1,"[{'week': 1, 'awayProTeamId': 34, 'date': 1725..."
22,FA,0,0,,FA,{},NaN,0,[]
23,Atl,12,1,Atlanta,Falcons,"{'1': [{'awayProTeamId': 23, 'date': 172581480...","{'16': -16001, '14': -14001, '15': -15001}",2,"[{'week': 1, 'awayProTeamId': 23, 'date': 1725..."
24,Buf,12,2,Buffalo,Bills,"{'1': [{'awayProTeamId': 22, 'date': 172581480...","{'16': -16002, '14': -14002, '15': -15002}",1,"[{'week': 1, 'awayProTeamId': 22, 'date': 1725..."
25,Chi,7,3,Chicago,Bears,"{'1': [{'awayProTeamId': 10, 'date': 172581480...","{'16': -16003, '14': -14003, '15': -15003}",2,"[{'week': 1, 'awayProTeamId': 10, 'date': 1725..."
26,Cin,12,4,Cincinnati,Bengals,"{'1': [{'awayProTeamId': 17, 'date': 172581480...","{'16': -16004, '14': -14004, '15': -15004}",1,"[{'week': 1, 'awayProTeamId': 17, 'date': 1725..."
27,Cle,10,5,Cleveland,Browns,"{'1': [{'awayProTeamId': 6, 'date': 1725827100...","{'16': -16005, '14': -14005, '15': -15005}",1,"[{'week': 1, 'awayProTeamId': 6, 'date': 17258..."
28,Dal,7,6,Dallas,Cowboys,"{'1': [{'awayProTeamId': 6, 'date': 1725827100...","{'16': -16006, '14': -14006, '15': -15006}",2,"[{'week': 1, 'awayProTeamId': 6, 'date': 17258..."
29,Den,14,7,Denver,Broncos,"{'1': [{'awayProTeamId': 7, 'date': 1725825900...","{'16': -16007, '14': -14007, '15': -15007}",1,"[{'week': 1, 'awayProTeamId': 7, 'date': 17258..."
30,Det,5,8,Detroit,Lions,"{'1': [{'awayProTeamId': 14, 'date': 172584120...","{'16': -16008, '14': -14008, '15': -15008}",2,"[{'week': 1, 'awayProTeamId': 14, 'date': 1725..."
31,GB,10,9,Green Bay,Packers,"{'1': [{'awayProTeamId': 9, 'date': 1725668100...","{'16': -16009, '14': -14009, '15': -15009}",2,"[{'week': 1, 'awayProTeamId': 9, 'date': 17256..."
32,Ten,5,10,Tennessee,Titans,"{'1': [{'awayProTeamId': 10, 'date': 172581480...","{'16': -16010, '14': -14010, '15': -15010}",1,"[{'week': 1, 'awayProTeamId': 10, 'date': 1725..."